BlogChallenge/Models/ErrorViewModel.cs
using System;

namespace BlogChallenge.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogChallenge/Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlogChallenge.Models
{
    public class PostViewModel
    {
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [Display(Name = "Identificador")]
        public string Id { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        public string Contenido { get; set; }

        public string Imagen { get; set; }

        public string Categoria { get; set; }

        public DateTime FechaDeCreacion { get; set; }

        public bool Activo { get; set; }
    }
}

BlogChallenge/Controllers/HomeController.cs
using BlogChallenge.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BlogChallenge.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogChallenge/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogChallenge.Models;
using Challenge.Database;

namespace BlogChallenge.Controllers
{
    public class PostsController : Controller
    {
        private readonly BlogDbContext _context;

        public PostsController(BlogDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> GetAll()
        {
            return View(await _context.Posts.Where(p => p.Activo == true).OrderByDescending(p => p.FechaDeCreacion).ToListAsync());
        }

        public async Task<IActionResult> Home()
        {
            return await GetAll();
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Posts.ToListAsync());
        }

        public async Task<IActionResult> GetById(string id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Home));
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id.Equals(id));
            if (post == null)
            {
                return RedirectToAction(nameof(Home));
            }

            return View(post);
        }

        public async Task<IActionResult> Details(string id)
        {
            return await GetById(id);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostViewModel post)
        {
            var p = _context.Posts.FirstOrDefault(x => x.Id.Equals(post.Id));

            if (p != null)
            {
                ModelState.AddModelError(string.Empty, "El id esta en uso. Escriba otro");
                return View("Create", post);
            }
            if (ModelState.IsValid && p == null)
            {
                post.FechaDeCreacion = DateTime.Now;
                post.Activo = true;
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Home));
            }
            return View(post);
        }

        public IActionResult FormularioDeEdicion()
        {
            return View();
        }

        public async Task<IActionResult> Update(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postViewModel = await _context.Posts.FindAsync(id);
            if (postViewModel == null)
            {
                return NotFound();
            }
            return View(postViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, PostViewModel postViewModel)
        {
            if (id != postViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var post = _context.Posts.FirstOrDefault(p => p.Id == id);
                    post.Titulo = postViewModel.Titulo;
                    post.Contenido = postViewModel.Contenido;
                    post.FechaDeCreacion = DateTime.Now;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostViewModelExists(postViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Home));
            }
            return View(postViewModel);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postViewModel = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (postViewModel == null)
            {
                return NotFound();
            }

            return View(postViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var postViewModel = await _context.Posts.FindAsync(id);
            postViewModel.Activo = false;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Home));
        }

        private bool PostViewModelExists(string id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }
    }
}

BlogChallenge/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BlogChallenge/Views/Posts/Create.cshtml
@model BlogChallenge.Models.PostViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Crear nueva entrada</h1>

<hr />

@using (Html.BeginForm("Create", "Posts", FormMethod.Post))
{
    <div class="form-group" style="width:20%">
        @Html.LabelFor(x => x.Id, new { @class = "control-label" })
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
        @Html.ValidationSummary(true, null, new { @class = "text-danger" })
    </div>
    <div class="form-group" style="width:35% ; float:left">
        @Html.LabelFor(x => x.Titulo, new { @class = "control-label" })
        @Html.TextBoxFor(x => x.Titulo, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Titulo, null, new { @class = "text-danger" })
    </div>
    <div class="form-group" style="width:30%; margin-left:5% ; float:left">
        @Html.LabelFor(x => x.Categoria, new { @class = "control-label" })
        @Html.TextBoxFor(x => x.Categoria, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Categoria, null, new { @class = "text-danger" })
    </div>
    <div class="form-group" style="margin-top:11%; width:70%">
        @Html.LabelFor(x => x.Contenido, new { @class = "control-label" })
        @Html.TextAreaFor(x => x.Contenido, new { @class = "form-control", @style = "height:20em", })
        @Html.ValidationMessageFor(x => x.Contenido, null, new { @class = "text-danger" })
    </div>
    <div class="form-group" style="width:70%">
        @Html.LabelFor(x => x.Imagen, new { @class = "control-label" })
        @Html.TextBoxFor(x => x.Imagen, new { @class = "form-control", @placeholder = "Ingrese la URL de la iamgen" })

    </div>
    <div class="form-group">
        <input type="submit" value="Publicar" class="btn btn-info search-button" />
    </div>
}

BlogChallenge/Views/Posts/Delete.cshtml
@model BlogChallenge.Models.PostViewModel

@{
    ViewData["Title"] = "Delete";
}


<h4>¿Desea eliminar este post?</h4>
<div>
    <div>
        <hr />
        <h4>@Html.DisplayFor(moodel => Model.Titulo)</h4>
        <dl class="row" style="margin-top:1em">
            <dd class="col-sm-10">
                @Html.DisplayTextFor(model => model.Contenido)
            </dd>
        </dl>
    </div>
    <div>
        <img src="@Html.DisplayFor(model => model.Imagen)" />
    </div>
    <div style="float:left; margin-right:2em">
        <span style="font-weight:700">@Html.DisplayName("ID"): </span><span>@Html.DisplayFor(model => model.Id)</span>
    </div>
    <div style="float:left; margin-right:2em">
        <span style="font-weight:700">@Html.DisplayNameFor(model => model.Categoria): </span><span>@Html.DisplayFor(model => model.Categoria)</span>
    </div>
    <div>
        <span style="font-weight:700">@Html.DisplayNameFor(model => model.FechaDeCreacion): </span><span>@Html.DisplayFor(model => model.FechaDeCreacion).</span>
    </div>
    <form asp-action="Delete" style="margin-top:2em">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver</a>
    </form>
</div>

BlogChallenge/Views/Posts/Details.cshtml
@model BlogChallenge.Models.PostViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(moodel => Model.Titulo)</h1>

<div>
    <hr />
    <dl class="row">
        <dd class="col-sm-10">
            @Html.DisplayTextFor(model => model.Contenido)
        </dd>
    </dl>
</div>
<div>
    <img src="@Html.DisplayFor(model => model.Imagen)" />
</div>
<div style="float:left; margin-right:2em">
    <span style="font-weight:700">@Html.DisplayName("ID"): </span><span>@Html.DisplayFor(model => model.Id)</span>
</div>
<div style="float:left; margin-right:2em">
    <span style="font-weight:700">@Html.DisplayNameFor(model => model.Categoria): </span><span>@Html.DisplayFor(model => model.Categoria)</span>
</div>
<div>
    <span style="font-weight:700">@Html.DisplayNameFor(model => model.FechaDeCreacion): </span><span>@Html.DisplayFor(model => model.FechaDeCreacion).</span>
</div>

<div style="margin-top:2em">
    <a asp-action="Update" asp-route-id="@Model.Id" class="btn btn-info search-button">Editar</a>
</div>

BlogChallenge/Views/Posts/FormularioDeEdicion.cshtml
@model BlogChallenge.Models.PostViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar post</h1>

<div class="container" style="padding:0">

    @using (Html.BeginForm("Update", "Posts", FormMethod.Get))
    {
        <label class="control-label" style="margin-top:2em; font-weight:700">Buscar Post</label>

        <div class="form-grup">
            <input type="text" class="form-control search-input" name="id" placeholder="ID del post" style="width:25%; float: left">
            <button type="submit" class="btn btn-info search-button" style="margin-left:1%">
                Buscar
            </button>
        </div>

    }

</div>
@using (Html.BeginForm("Update", "Posts", FormMethod.Post))
{
    <div class="form-group" style="width:45%; margin-top:2em">
        @Html.LabelFor(x => x.Titulo, new { @class = "control-label" })
        @Html.TextBoxFor(x => x.Titulo, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Titulo, null, new { @class = "text-danger" })
    </div>
    <div class="form-group" style="margin-top:2em">
        @Html.LabelFor(x => x.Contenido, new { @class = "control-label" })
        @Html.TextAreaFor(x => x.Contenido, new { @class = "form-control", @style = "height:20em; width:70%" })
        @Html.ValidationMessageFor(x => x.Contenido, null, new { @class = "text-danger" })
    </div>
    <div class="form-group" style="margin-top:2em">
        <input type="submit" class="btn btn-info search-button" value="Editar" />
    </div>
}

BlogChallenge/Views/Posts/Home.cshtml
@model IEnumerable<BlogChallenge.Models.PostViewModel>

@{
    ViewData["Title"] = "Home";
}

<h1>Inicio</h1>


<div class="container" style="padding:0">

    @using (Html.BeginForm("Details", "Posts", FormMethod.Get))
    {
        <label class="control-label" style="margin-top:2em; font-weight:700">Buscar Post</label>

        <div class="form-grup">
            <input type="text" class="form-control search-input" name="id" placeholder="ID del post" style="width:25%; float: left">
            <button type="submit" class="btn btn-info search-button" style="margin-left:1%">
                Buscar
            </button>
        </div>
        @Html.ValidationSummary(true)
    }

</div>

<table class="table" style="margin-top:2em">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("ID")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td style="float: right">
                    <a  style="color:#17a2b8" asp-action="Update" asp-route-id="@item.Id">Editar</a> |
                    <a style="color:#17a2b8" asp-action="Details" asp-route-id="@item.Id">Detalle</a> |
                    <a style="color:#17a2b8" asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

BlogChallenge/Views/Posts/Index.cshtml
@model IEnumerable<BlogChallenge.Models.PostViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contenido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDeCreacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contenido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaDeCreacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activo)
            </td>
            <td>
                <a asp-action="Update" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BlogChallenge/Views/Posts/Update.cshtml
@model BlogChallenge.Models.PostViewModel

@{
    ViewData["Title"] = "Edit";
}


<h1>Editar post</h1>


@using (Html.BeginForm("Update", "Posts", FormMethod.Post))
{
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group" style="width:45%; margin-top:2em">
        @Html.LabelFor(x => x.Titulo, new { @class = "control-label" })
        @Html.TextBoxFor(x => x.Titulo, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Titulo, null, new { @class = "text-danger" })
    </div>
    <div class="form-group" style="margin-top:2em">
        @Html.LabelFor(x => x.Contenido, new { @class = "control-label" })
        @Html.TextAreaFor(x => x.Contenido, new { @class = "form-control", @style = "height:20em; width:70%" })
        @Html.ValidationMessageFor(x => x.Contenido, null, new { @class = "text-danger" })
    </div>
    <div class="form-group" style="margin-top:2em">
        <input type="submit" class="btn btn-info search-button" value="Editar" />
    </div>
}


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogChallenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogChallenge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @Html.ActionLink("BlogChallenge.com", "Home", "Posts", null, new { @class = "navbar-brand" })
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @Html.ActionLink("Inicio", "Home", "Posts", null, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Crear post", "Create", "Posts", null, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Editar post", "FormularioDeEdicion", "Posts", null, new { @class = "nav-link text-dark" })
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BlogChallenge - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>